#!/usr/bin/env php
<?php

/**
 * @file
 * Script to fetch OAI-PMH records and report out specific aspects of
 * the aggregated set of records.
 */

require 'vendor/autoload.php';
use League\CLImate\CLImate;

// Read the .ini file.
if (file_exists(trim($argv[1]))) {
    $config = parse_ini_file(trim($argv[1]), true);
} else {
    print "Cannot find configuration file " . trim($argv[1]) . "\n";
    exit;
}

/**
 * Set up configuration values.
 */
$save_records = isset($config['general']['save_records']) ?  $config['general']['save_records'] : true;
$output_dir = $config['general']['output_dir'];
$endpoint_url = $config['oai']['endpoint'];
$metadata_prefix = isset($config['oai']['metadata_prefix']) ?  $config['oai']['metadata_prefix'] : 'oai_dc';
$namespace = isset($config['oai']['namespace']) ?  $config['oai']['namespace'] : 'http://purl.org/dc/elements/1.1/';
$set_spec = isset($config['oai']['set_spec']) ?  $config['oai']['set_spec'] : null;
$unique_element_values_path = isset($config['reports']['unique_element_values_output_file']) ?
    $config['reports']['unique_element_values_output_file'] : 'unique_element_values_output_file.txt';

$client = new \Phpoaipmh\Client($endpoint_url);
$endpoint = new \Phpoaipmh\Endpoint($client);

if ($save_records) {
    @mkdir($output_dir);
}

print "Fetching records from $endpoint_url...\n";
$recs = $endpoint->listRecords($metadata_prefix, null, null, $set_spec);

$num_recs = $recs->getTotalRecordCount();
if (!is_null($num_recs)) {
    $climate = new League\CLImate\CLImate;
    $progress = $climate->progress()->total($num_recs);
}

// Define variables used in reports.
$element_counts = array();
$element_unique_values = array();

// Main program loop.
$record_num = 0;
foreach($recs as $rec) {
    $record_num++;
    $identifier = urlencode($rec->header->identifier);

    if (!is_null($num_recs)) {
        $progress->current($record_num);
    }

    // Element count report.
    $elements = get_elements($rec->asXML(), $namespace);
    foreach ($elements as $element) {
        if (array_key_exists($element, $element_counts)) {
            $element_counts[$element]++;
        }
        else {
            $element_counts[$element] = 1;
        }
    }

    // Unique element values report.
    $element_values = get_element_values($rec->asXML(), $namespace);
    foreach ($element_values as $element_name => $values) {
        if (!array_key_exists($element_name, $element_unique_values)) {
            $element_unique_values[$element_name] = array();
        }
        foreach ($values as $value) {
            if (!strlen($value)) {
                $value = '""';
            }
            if (!in_array($value, $element_unique_values[$element_name])) {
                $element_unique_values[$element_name][] = $value;
            }
        }
    }

    if ($save_records) {
        $output_path = $output_dir . DIRECTORY_SEPARATOR . $identifier . '.oai.xml';
        file_put_contents($output_path, $rec->asXML());
    }
}
print "Fetched $record_num records from $endpoint_url.\n";

// Element count report.
if (isset($config['reports']['reports']) && in_array('element_count', $config['reports']['reports'])) {
    print "\nElement\tNumber occurances in all records\n";
    print "========================================\n";
    foreach ($element_counts as $element => $count) {
        print "$element\t$count\n";
    }
}
// Unique element values report.
if (isset($config['reports']['reports']) && in_array('unique_element_values', $config['reports']['reports'])) {
    $output = '';
    foreach ($element_unique_values as $element => $values) {
        natsort($values);
        $output .= $element . "\n========================\n";
        if (isset($values)) {
            foreach ($values as $value) {
                if (isset($value)) {
                    $output .= $value . "\n";
                }
            }
            $output .= "\n\n";
        }
    }

    file_put_contents($unique_element_values_path, $output);
    print "\nUnique element values report is in $unique_element_values_path.\n";
}

/**
 * Gets element names in the OAI-PMH metadata.
 *
 * @param string $oai_record
 *   The serialized XML of the OAI-PMH record.
 * @param string $namespace
 *   The namespace URI of the metadata we want to
 *   inspect, e.g., http://purl.org/dc/elements/1.1/.
 *
 * @return array
 *   An array containing the elements and their values
 *   in each one of the OAI-PMH records. These elements
 *   are filtered to include only those in the specified
 *   namespace.
 */
function get_elements($oai_record, $namespace) {
    $elements = array();
    $dom = new DOMDocument;
    $dom->loadXML($oai_record);
    foreach ($dom->getElementsByTagNameNS($namespace, '*') as $element) {
        $elements[] = $element->nodeName;
    }
    return $elements;
}

/**
 * Parses the XML element values into an array.
 *
 * @param string $oai_record
 *   The serialized XML of the OAI-PMH record.
 * @param string $namespace
 *   The namespace URI of the metadata we want to
 *   inspect, e.g., http://purl.org/dc/elements/1.1/.
 *
 * @return array
 *   An associative array containing element name => element values.
 */
function get_element_values($oai_record, $namespace) {
  $values = array();
  $dom = new DOMDocument;
  $dom->loadXML($oai_record);
  $elements = $dom->getElementsByTagNameNS($namespace, '*');
  foreach ($elements as $e) {
    if (!array_key_exists($e->nodeName, $values)) {
      $values[$e->nodeName] = array();
      $values[$e->nodeName][] = $e->nodeValue;
    }
    else {
      $values[$e->nodeName][] = $e->nodeValue;
    }
  }
  return $values;
}
