#!/usr/bin/env php
<?php

/**
 * @file
 * Script to fetch OAI-PMH records and report out specific aspects of
 * the aggregated set of records.
 */

require 'vendor/autoload.php';
use League\CLImate\CLImate;

// Read the .ini file.
if (file_exists(trim($argv[1]))) {
    $config = parse_ini_file(trim($argv[1]), true);
} else {
    print "Cannot find configuration file " . trim($argv[1]) . "\n";
    exit;
}

/**
 * Set up configuration values.
 */
$save_records = isset($config['general']['save_records']) ?  $config['general']['save_records'] : true;
$output_dir = $config['general']['output_dir'];
$endpoint_url = $config['oai']['endpoint'];
$metadata_prefix = isset($config['oai']['metadata_prefix']) ?  $config['oai']['metadata_prefix'] : 'oai_dc';
$namespace = isset($config['oai']['namespace']) ?  $config['oai']['namespace'] : 'http://purl.org/dc/elements/1.1/';
$set_spec = isset($config['oai']['set_spec']) ?  $config['oai']['set_spec'] : null;

$client = new \Phpoaipmh\Client($endpoint_url);
$endpoint = new \Phpoaipmh\Endpoint($client);

if ($save_records) {
    @mkdir($output_dir);
}

print "Fetching records from $endpoint_url...\n";
$recs = $endpoint->listRecords($metadata_prefix, null, null, $set_spec);

$num_recs = $recs->getTotalRecordCount();
if (!is_null($num_recs)) {
    $climate = new League\CLImate\CLImate;
    $progress = $climate->progress()->total($num_recs);
}

$element_counts = array();

$record_num = 0;
foreach($recs as $rec) {
    $record_num++;
    $identifier = urlencode($rec->header->identifier);

    if (!is_null($num_recs)) {
        $progress->current($record_num);
    }

    // Element count report.
    $elements = get_elements($rec->asXML(), $namespace);
    foreach ($elements as $element) {
        if (array_key_exists($element, $element_counts)) {
            $element_counts[$element]++;
        }
        else {
            $element_counts[$element] = 1;
        }
    }

    if ($save_records) {
        $output_path = $output_dir . DIRECTORY_SEPARATOR . $identifier . '.oai.xml';
        file_put_contents($output_path, $rec->asXML());
    }
}
print "Fetched $record_num records from $endpoint_url.\n";

// Element count report.
if (isset($config['reports']['reports']) && in_array('element_count', $config['reports']['reports'])) {
    print "\nElement\tNumber occurances in all records\n";
    print "========================================\n";
    foreach ($element_counts as $element => $count) {
        print "$element\t$count\n";
    }
}

/**
 * Selects XPath expressions to elements.
 *
 * @param string $oai_record
 *   The serialized XML of the OAI-PMH record.
 * @param string $namespace
 *   The namespace of the metadata we want to
 *   inspect, e.g., 'oai_dc', 'mods', etc.
 *
 * @return array
 *   An array containing the elements and their values
 *   in each one of the OAI-PMH records. These elements
 *   are filtered to the specified namespace.
 */
function get_elements($oai_record, $namespace) {
    $elements = array();
    $dom = new DOMDocument;
    $dom->loadXML($oai_record);
    // @todo: Account for repeated elements.
    foreach ($dom->getElementsByTagNameNS($namespace, '*') as $element) {
        $elements[] = $element->nodeName;
    }
    return $elements;
}
